version: '3'

services:
  db: 
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: NUS-carpark-data
      MYSQL_USER: user
      MYSQL_PASSWORD: root_password
    expose:
      - 3306

  user:
    build:
      context: .
      dockerfile: user_dockerfile
    volumes:
      - type: bind
        source: data/
        target: /data/
    ports:
      - "3307:3306"
    depends_on:
      - db
    stdin_open: true
    tty: true

  
  # app:
  #   build: 
  #     context: .
  #     dockerfile: dash_dockerfile.txt
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8050:8050"
  #   stdin_open: true
  #   tty: true
