version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root_password
      DATABASE_NAME: NUS-carpark-data
    build:
      context: .
      dockerfile: mysql_dockerfile.txt
    env_file:
      - .env
    ports:
      - "3307:3306"
  
  app:
    build: 
      context: .
      dockerfile: dash_dockerfile.txt
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8050:8050"
