version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: mysql_dockerfile.txt
    container_name: db
    volumes:
      - type: bind
        source: data/
        target: /data/
    ports:
      - "3307:3306"
    stdin_open: true
    tty: true

  
  # app:
  #   build: 
  #     context: .
  #     dockerfile: dash_dockerfile.txt
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8050:8050"
  #   stdin_open: true
  #   tty: true
