version: '3'

services:
  db: 
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: NUS-carpark-data
      MYSQL_USER: user
      MYSQL_PASSWORD: root_password

  user:
    build:
      context: .
      dockerfile: user_dockerfile
    volumes:
      - type: bind
        source: data/
        target: /data/
    ports:
      - "8050:8050"
    stdin_open: true
    tty: true